### ISSUE TITLE
lib/helper.rb:163: syntax error, unexpected end-of-input, expecting keyword_end

### ISSUE THREAD

**Issue by coip** [softvis/churn-charts#2]
Reproduction steps, fresh clone:

```
$ git clone https://github.com/softvis/churn-charts.git
Cloning into 'churn-charts'...
remote: Enumerating objects: 161, done.
remote: Total 161 (delta 0), reused 0 (delta 0), pack-reused 161
Receiving objects: 100% (161/161), 136.97 KiB | 1.67 MiB/s, done.
Resolving deltas: 100% (77/77), done.
$ cd churn-charts/
# assuming gitlog.txt input file is in PWD
$ ./app.rb
```

```
Traceback (most recent call last):
        2: from ./app.rb:6:in `<main>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': /home/coip/lab/churn/churn-charts/lib/helper.rb:155: syntax error, unexpected tSYMBEG, expecting '}' (SyntaxError)
          :weight => weight,
          ^
/home/coip/lab/churn/churn-charts/lib/helper.rb:163: syntax error, unexpected end-of-input, expecting keyword_end```

**Comment by flacle** [comment]
Hi @coip see https://github.com/softvis/churn-charts/pull/1

**Comment by coip** [comment]
Hi @flacle 

This issue(#2) is to assert an issue with the project; there wasn't an issue for the PR to fix prior.

The PR you've linked does address the issue, though if the maintainer wants to address this issue by accepting #1, theyre also going to roll in support for `jsx`/`ts` files, which are **absolutely unrelated** to the syntax issue preventing use.

So I opened this issue and a related pullrequest which addresses **only this issue**. 

#### I do not want the maintainer to have to accept `jsx`/`ts` if they want the syntax error fixed.

**Comment by flacle** [comment]
Hi @coip, I have a habit of checking PRs by date in ascending order and encountered the other one first. Indeed, it's up to the maintainer to decide.
